services:
  - type: web
    name: nikecatering
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: SENDGRID_API_KEY
        value: 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
      - key: DEFAULT_FROM_EMAIL
        value: websoiree1@gmail.com
      - key: EMAIL_HOST_USER
        value: apikey
      - key: EMAIL_HOST_PASSWORD
        value: foxx uhhv hhbq ticf
      - key: PG_DB
        value: soireeweb
      - key: PG_USER
        value: postgres
      - key: PG_PASS
        value: 123
      - key: PG_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: PG_PORT
        value: 5432
      - key: DJANGO_ENV
        value: prod