# Generated by Django 5.2.1 on 2025-07-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mobilepost',
            table='mobile_post',
        ),
        migrations.AlterModelTable(
            name='mobilepostimage',
            table='mobile_post_image',
        ),
    ]
