# Generated by Django 4.1.13 on 2025-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
