# Generated by Django 5.2.1 on 2025-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatuslog',
            name='total_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount due for payment (only set for PAYMENT label)', max_digits=10, null=True),
        ),
    ]
