# Generated by Django 5.2.1 on 2025-07-12 07:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mobilepost_created_by_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft / Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=60)),
                ('pax', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('color_hex', models.CharField(max_length=7)),
                ('package', models.CharField(max_length=40)),
                ('dishes', models.TextField(help_text='Comma-separated list of dishes')),
                ('pasta', models.CharField(max_length=60)),
                ('drink', models.CharField(max_length=60)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_request',
                'ordering': ('-created_at',),
            },
        ),
    ]
