# Generated by Django 5.2.1 on 2025-08-13 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
    ]
