# Generated by Django 5.2.1 on 2025-07-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chat'),
        ),
    ]
