# Generated by Django 5.2.1 on 2025-07-12 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bookingrequest_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_booking', to='main.chat'),
        ),
    ]
