# Generated by Django 5.2.1 on 2025-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilepostimage',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
