# Generated by Django 5.2.1 on 2025-07-21 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bookingrequest_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('BACKDROP', 'Backdrop'), ('PAYMENT', 'Payment'), ('LOGISTICS', 'Logistics'), ('CATERING', 'Catering')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('PARTIALLY_PAID', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='main.bookingrequest')),
            ],
            options={
                'db_table': 'event_status_log',
                'unique_together': {('booking', 'label')},
            },
        ),
        migrations.CreateModel(
            name='EventStatusAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_attachments/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_status_attachments', to='main.bookingrequest')),
                ('status_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='main.eventstatuslog')),
            ],
            options={
                'db_table': 'event_status_attachment',
                'unique_together': {('booking', 'status_log')},
            },
        ),
    ]
