# Generated by Django 5.2.1 on 2025-08-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mobilepostimage_cloudinary_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilepostimage',
            name='cloudinary_public_id',
        ),
        migrations.AddField(
            model_name='mobilepostimage',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_posts/'),
        ),
    ]
