# Generated by Django 5.2.1 on 2025-07-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventstatuslog_eventstatusattachment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventstatusattachment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='eventstatusattachment',
            name='status_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.eventstatuslog'),
        ),
        migrations.AlterUniqueTogether(
            name='eventstatusattachment',
            unique_together={('booking', 'status_log', 'file')},
        ),
    ]
