# Generated by Django 5.2.1 on 2025-08-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_mobilepostimage_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatusattachment',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
