# Generated by Django 5.2.1 on 2025-08-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_eventstatusattachment_cloudinary_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventstatusattachment',
            unique_together={('booking', 'status_log', 'file', 'cloudinary_url')},
        ),
    ]
