# Generated by Django 5.2.1 on 2025-08-15 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_eventstatusattachment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='location',
            new_name='venue',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='celebrant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='file',
            field=models.FileField(default='', upload_to='event_attachments/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MobileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile_reviews/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.mobilereview')),
            ],
            options={
                'db_table': 'mobile_review_image',
            },
        ),
    ]
