# Generated by Django 5.2.1 on 2025-08-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_location_bookingrequest_venue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='color_hex',
            new_name='color_motif',
        ),
        migrations.RenameField(
            model_name='bookingrequest',
            old_name='file',
            new_name='floorplan',
        ),
    ]
