# Generated by Django 5.2.1 on 2025-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_color_hex_bookingrequest_color_motif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='color_motif',
            field=models.CharField(max_length=255),
        ),
    ]
