# Generated by Django 5.2.1 on 2025-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_bookingrequest_color_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='floorplan',
            field=models.FileField(upload_to='booking/'),
        ),
    ]
