# Generated by Django 5.2.1 on 2025-08-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_bookingrequest_floorplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
    ]
