# Generated by Django 5.2.1 on 2025-08-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_review_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
