# Generated by Django 5.2.1 on 2025-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='floorplan',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='booking_floorplans/'),
        ),
    ]
