# Generated by Django 5.2.1 on 2025-08-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_bookingrequest_floorplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilereviewimage',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MobileReview',
        ),
        migrations.DeleteModel(
            name='MobileReviewImage',
        ),
    ]
