# Generated by Django 5.2.1 on 2025-08-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_mobilereviewimage_review_review_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='floorplan',
            field=models.CharField(blank=True, help_text='Floor plan filename (e.g., 120_pax_2_icgqtv.png)', max_length=200, null=True),
        ),
    ]
