# Generated by Django 5.2.1 on 2025-08-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_bookingrequest_floorplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='floorplan_display_name',
            field=models.CharField(blank=True, help_text='User-friendly floor plan name (e.g., Floor Plan 1)', max_length=100, null=True),
        ),
    ]
