# Generated by Django 5.2.1 on 2025-08-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_adminnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnotification',
            old_name='booking_request',
            new_name='booking',
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('new_booking', 'New Booking Request'), ('payment_received', 'Payment Received'), ('message_received', 'New Message')], default='new_booking', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
