# Generated by Django 5.2.1 on 2025-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
