# Generated by Django 5.2.1 on 2025-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_review_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='theme_name',
            field=models.CharField(blank=True, help_text='Name of the selected theme', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='theme_urls',
            field=models.JSONField(blank=True, help_text='All image URLs for the selected theme', null=True),
        ),
    ]
