# Generated by Django 5.2.1 on 2025-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_theme_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='floorplan',
            field=models.TextField(blank=True, help_text='Floor plan filename (e.g., 120_pax_2_icgqtv.png) or AI estimations for custom layouts', null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='floorplan_display_name',
            field=models.CharField(blank=True, help_text='User-friendly floor plan name (e.g., Floor Plan 1, AI Generated Floor Plan)', max_length=100, null=True),
        ),
    ]
