# Generated by Django 5.2.1 on 2025-09-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_bookingrequest_floorplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='floorplan_display_name',
            field=models.TextField(blank=True, help_text='User-friendly floor plan name or AI estimation text (can be long for AI-generated content)', null=True),
        ),
    ]
