# Generated by Django 5.2.1 on 2025-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_increase_floorplan_display_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatuslog',
            name='label',
            field=models.CharField(choices=[('BACKDROP', 'Backdrop'), ('PAYMENT', 'Payment'), ('LOGISTICS', 'Logistics'), ('CATERING', 'Catering'), ('FOOD_MENU', 'Food Menu')], max_length=30),
        ),
    ]
