import os
from decouple import config
from pathlib import Path
import cloudinary
import cloudinary.uploader
import cloudinary.api


"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Hosts
PROD_HOST = config('PROD_HOST', default='https://nikescateringservices.com').rstrip('/')
LOCAL_HOST = config('LOCAL_HOST', default='http://localhost:8001').rstrip('/')


# Environment (dev/prod)
ENVIRONMENT = config('DJANGO_ENV', default='dev')  # 'prod' or 'dev'
DEBUG = ENVIRONMENT != 'prod'

# Base URL to be used in templates and static/media settings
BASE_URL = PROD_HOST if ENVIRONMENT == 'prod' else LOCAL_HOST

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-^j__tk^0+jp^cu^p%uyxpb-s6o^#=&!tty-9!g*9n&di_n#0jf'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l(y@)op3+!yl^6fy^i&atbc1&54bi!v&9eidoy+ddq2d#k@_l7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    PROD_HOST.replace('https://', '').replace('http://', ''),
    f"www.{PROD_HOST.replace('https://', '').replace('http://', '')}",
    'localhost',
    '127.0.0.1',
    'soireeweb.onrender.com',
    "soiree-experimental.onrender.com",
    'www.nikescateringservices.com',
    'nikescateringservices.com',
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [BASE_DIR / 'main' / 'static', 
    BASE_DIR / "static",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'django.contrib.staticfiles',
    'fuzzywuzzy',
    'cloudinary_storage',
    'cloudinary',
    'main',
    'channels',
]

MIDDLEWARE = [
    'config.middleware.BypassRefererCheckMiddleware',
    'config.middleware.RedirectToWwwMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'main' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processor.global_settings',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Use in-memory channel layer (no Redis)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Development vs Production Database Configuration
if ENVIRONMENT == 'dev':
    # SQLite for development (easier setup)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL for production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('PG_DB'),
            'USER': config('PG_USER'),
            'PASSWORD': config('PG_PASS'),
            'HOST': config('PG_HOST'),
            'PORT': config('PG_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# DeepAI API Configuration
DEEPAI_API_KEY = 'c6ea7310-add9-441d-9a53-019f2f12da1f'  # Replace with your actual DeepAI API key

ASGI_APPLICATION = "config.asgi.application"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'main.User'

CSRF_TRUSTED_ORIGINS = [
    BASE_URL,
    "http://localhost:19006",
    "http://127.0.0.1:3000",
    "https://soireeweb.onrender.com",
    "https://nikescateringservices.com", # Domain
    "https://www.nikescateringservices.com",
    "https://soiree-experimental.onrender.com"# Domain
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:19006",
    "http://127.0.0.1:3000",
    "https://soireeweb.onrender.com",
    "https://nikescateringservices.com", # Domain
    "https://www.nikescateringservices.com",
    "https://soiree-experimental.onrender.com"# Domain
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# MEDIA_URL = '/media/'



if ENVIRONMENT == 'prod':
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    # MEDIA_URL = f"/"  # optional: Cloudinary will auto-handle
  
    cloudinary.config( 
        cloud_name = config('CLOUDINARY_CLOUD_NAME'), 
        api_key = config('CLOUDINARY_API_KEY'), 
        api_secret = config('CLOUDINARY_API_SECRET'), # Click 'View API Keys' above to copy your API secret
        secure=True
    )
    
    # MEDIA_URL = f"https://res.cloudinary.com/{config('CLOUDINARY_CLOUD_NAME')}/"
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"


# SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# If needed
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_ALLOW_CREDENTIALS = True

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='enricosuarez777@gmail.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='jchx oyls rhsg ycmn')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)